name: ci

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  tests:
    steps:
      - name: Install
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: Test
        run: COVERAGE=true ember exam --split=8 --parallel
